### ISSUE TITLE
Barrels throwing errors: export * from './components'

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/vuejs-typescript-lob-examples#10]
Is this supported by Vue?

Steps to reproduce it:

_./src/components/index.ts_

```typescript
export * from './users-table.vue';
```
_./src/views/Home.vue_

```diff
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
- import UsersTable from '@/components/users-table.vue';
+ import {UsersTable} from '@/components';
```

This throws an error, tried as well to remove _export default_ and other flavours but no success.

Any clue on this? What I'm doing wrong?

**Comment by LissetteIbnz** [comment]
Vue files currently does not support type exports... check this https://github.com/vuejs/vue-loader/issues/1281
